workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - keystore
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
    scripts:
      - name: Debug Setup
        script: |
          echo "=== Environment Debug ==="
          flutter doctor -v
          java -version
          cd android && ./gradlew --version
          cd ..

      - name: Clean and Prepare
        script: |
          flutter clean
          rm -rf android/build
          flutter pub get

      - name: Build with Full Logs
        script: |
          cd android
          ./gradlew clean --stacktrace --info
          ./gradlew assembleRelease --stacktrace --info --scan
          cd ..
          flutter build apk --release --verbose

      - name: Artifact Collection
        script: |
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/
          ls -la build/outputs/apk/
    artifacts:
      - build/outputs/apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com