workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - keystore
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"  # Standard Java 11 path
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"  # More stable builds
    scripts:
      - name: Verify Environment
        script: |
          echo "=== Environment Verification ==="
          flutter doctor -v
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          
      - name: Clean and Prepare
        script: |
          flutter clean
          rm -rf android/build
          flutter pub get
          
      - name: Build with Debugging
        script: |
          cd android
          ./gradlew clean assembleRelease --stacktrace --info --scan
          cd ..
          
      - name: Collect Artifacts
        script: |
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/
          ls -lh build/outputs/apk/
    artifacts:
      - build/outputs/apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com