workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - keystore
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx4096m"
    
    scripts:
      # ======================
      # 1. NUCLEAR GRADLE RESET
      # ======================
      - name: Nuclear Gradle Reset
        script: |
          echo "=== COMPLETE GRADLE RESET ==="
          rm -rf android/.gradle android/gradle android/gradlew* android/local.properties
          flutter create --platforms android .
          cd android
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip" > gradle/wrapper/gradle-wrapper.properties
          echo -e "org.gradle.unsafe.configuration-cache=false\norg.gradle.enterprise.buildScan.publish.never=true" > gradle.properties
          ./gradlew --version || (echo "Gradle validation failed"; exit 1)
          cd ..

      # ======================
      # 2. ANDROIDX CONFIG
      # ======================
      - name: Enable AndroidX
        script: |
          echo "=== Enabling AndroidX ==="
          echo -e "\n# AndroidX Configuration\nandroid.useAndroidX=true\nandroid.enableJetifier=true" >> android/gradle.properties

      # ======================
      # 3. ENVIRONMENT SETUP
      # ======================
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties

      - name: Setup Java Environment
        script: |
          JAVA_HOME=$(/usr/libexec/java_home -v 11 2>/dev/null || /usr/libexec/java_home -v 17 2>/dev/null)
          if [ -z "$JAVA_HOME" ]; then
            echo "ERROR: No compatible Java installation found"
            exit 1
          fi
          echo "JAVA_HOME=$JAVA_HOME" >> $CM_ENV

      - name: Verify Environment
        script: |
          flutter doctor -v
          java -version

      # ======================
      # 4. GRADLE CONFIGURATION
      # ======================
      - name: Configure Gradle
        script: |
          cd android
          sed -i.bak 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip|' gradle/wrapper/gradle-wrapper.properties
          sed -i.bak 's|com.android.tools.build:gradle:[0-9.]*|com.android.tools.build:gradle:8.0.0|' build.gradle
          echo "android { compileOptions { sourceCompatibility JavaVersion.VERSION_11; targetCompatibility JavaVersion.VERSION_11 } }" >> app/build.gradle
          cd ..

      # ======================
      # 5. BUILD PROCESS
      # ======================
      - name: Run Release Build
        script: |
          echo "=== Starting Build ==="
          flutter clean
          cd android
          ./gradlew clean assembleRelease \
            --no-configuration-cache \
            --no-scan \
          cd ..

          flutter build apk --release

      # ======================
      # 6. ARTIFACT VERIFICATION
      # ======================
      - name: Verify and Package Artifacts
        script: |
          if [ ! -d "build/app/outputs/flutter-apk" ]; then
            echo "ERROR: No APK directory found!"
            exit 1
          fi
          
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/

    artifacts:
      - build/outputs/apk/*.apk
      - android/gradle/wrapper/gradle-wrapper.properties
      - android/build.gradle
      - android/app/build.gradle

    publishing:
      email:
        recipients:
          - your.email@example.com