workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - keystore
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx4096m"
    scripts:
      # PHASE 1: ENVIRONMENT SETUP
      - name: Setup Environment
        script: |
          echo "=== Environment Configuration ==="
          flutter doctor -v
          java -version
          cd android && ./gradlew --version && cd ..

      # PHASE 2: PROJECT PREPARATION
      - name: Clean Project
        script: |
          echo "=== Cleaning Project ==="
          flutter clean
          rm -rf android/build app/build
          flutter pub get

      # PHASE 3: GRADLE BUILD WITH DEBUGGING
      - name: Run Gradle with Full Diagnostics
        script: |
          echo "=== Running Gradle with Debug ==="
          cd android
          ./gradlew clean \
            assembleRelease \
            --no-daemon \
            --stacktrace \
            --info \
            --scan \
            --console=plain \
            -Pverbose=true \
            > gradle_log.txt 2>&1 || (cat gradle_log.txt && exit 1)
          cat gradle_log.txt | grep -i "error\|fail\|exception"
          cd ..

      # PHASE 4: FLUTTER BUILD
      - name: Build Flutter APK
        script: |
          echo "=== Building Flutter APK ==="
          flutter build apk \
            --release \
            --verbose \
            --build-number=$BUILD_NUMBER \
            --no-shrink

      # PHASE 5: ARTIFACT HANDLING
      - name: Collect and Verify Artifacts
        script: |
          echo "=== Final Artifacts ==="
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/
          
          # Verify APK exists
          if [ ! -f "build/outputs/apk/app-release.apk" ]; then
            echo "ERROR: APK not generated!"
            exit 1
          fi
          
          echo "APK generated successfully:"
          ls -lh build/outputs/apk/
          echo "APK info:"
          unzip -l build/outputs/apk/app-release.apk | grep -i "libflutter.so"

    artifacts:
      - build/outputs/apk/*.apk
      - android/gradle_log.txt

    publishing:
      email:
        recipients:
          - your.email@example.com
      scripts:
        - name: Build Report
          script: |
            echo "=== Build Diagnostics ==="
            echo "Java version:"
            java -version
            echo "Flutter version:"
            flutter --version
            echo "Gradle version:"
            cd android && ./gradlew --version && cd ..
            echo "APK contents:"
            unzip -l build/outputs/apk/*.apk | head -30