workflows:
  android-release:
    name: Android Release
    environment:
      groups:
        - keystore
      vars:
        BUILD_NUMBER: $BUILD_NUMBER
    scripts:
      - name: Setup environment
        script: |
          flutter --version
          java -version
          flutter pub cache repair
          
      - name: Install dependencies
        script: |
          flutter pub get
          cd android && ./gradlew dependencies
          
      - name: Clean project
        script: |
          flutter clean
          cd android && ./gradlew clean
          
      - name: Build APK
        script: |
          flutter build apk --release \
            --build-number=$BUILD_NUMBER \
            --verbose || {
              echo "Build failed! Check logs above"
              cd android && ./gradlew assembleRelease --stacktrace
              exit 1
            }
            
      - name: Prepare artifacts
        script: |
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/
          ls -la build/outputs/apk/
    artifacts:
      - build/outputs/apk/*.apk
    publishing:
      email:
        recipients:
          - sujith.ks@wayvida.com