workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - keystore
    scripts:
      - name: Auto-detect Java Home
        script: |
          # Find the first available Java installation
          JAVA_HOME=$(/usr/libexec/java_home -v 11 2>/dev/null || /usr/libexec/java_home -v 17 2>/dev/null)
          if [ -z "$JAVA_HOME" ]; then
            echo "ERROR: No Java installation found"
            exit 1
          fi
          echo "Using JAVA_HOME: $JAVA_HOME"
          echo "JAVA_HOME=$JAVA_HOME" >> $CM_ENV

      - name: Verify Java Installation
        script: |
          echo "=== Java Version ==="
          java -version
          javac -version
          echo "JAVA_HOME=$JAVA_HOME"
          ls -la "$JAVA_HOME/bin/java"

      - name: Setup Build Environment
        script: |
          flutter clean
          rm -rf android/build
          flutter pub get

      - name: Run Gradle Build
        script: |
          cd android
          ./gradlew clean assembleRelease --stacktrace --info --scan
          cd ..

      - name: Collect Artifacts
        script: |
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/
    artifacts:
      - build/outputs/apk/*.apk