workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - keystore
    scripts:
      # - name: Setup Kotlin and Gradle
      #   script: |
      #     # Set compatible Kotlin version
      #     sed -i '' "s/kotlin_version = '1.9.20'/kotlin_version = '1.8.10'/" android/build.gradle
          
      #     # Verify Gradle wrapper
      #     cd android && ./gradlew --version
      - name: Setup environment
        script: |
          flutter pub get
          flutter clean

      - name: Generate Gradle wrapper
        script: |
          cd android
          flutter pub get
          flutter clean
          gradle wrapper --gradle-version 7.5
      - name: Downgrade Kotlin
        script: |
          sed -i.bak 's/kotlin_version = .*/kotlin_version = "1.8.10"/' android/build.gradle
          sed -i.bak 's/gradle:7.[0-9].*/gradle:7.6.0"/' android/build.gradle

      - name: Build APK
        script: |
          flutter build apk --release --verbose

      - name: Prepare artifacts
        script: |
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/
    artifacts:
      - build/outputs/apk/*.apk