workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - keystore
    scripts:
      - name: Setup environment
        script: |
          flutter pub get
          flutter clean

      - name: Generate Gradle wrapper
        script: |
          cd android
          flutter pub get
          flutter clean
          gradle wrapper --gradle-version 7.5

      - name: Build APK
        script: |
          flutter build apk --release --verbose

      - name: Prepare artifacts
        script: |
          mkdir -p build/outputs/apk
          cp build/app/outputs/flutter-apk/*.apk build/outputs/apk/
    artifacts:
      - build/outputs/apk/*.apk